channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - numpy
  - scipy
  - matplotlib
  - scikit-learn
  - pandas
  - pytorch::pytorch=1.2.0
  - joblib
  - cxx-compiler
  - dill
  - swig
  - pip
  - pip:
    - tick==0.6.0
    - pynvml
  - tqdm

